[package]
name = "remu_core"
version = "0.1.0"
edition = "2024"

[dependencies]
remu_macro = { path = "../remu_macro" }

clap = { version = "4.5.54", features = [ "derive", "color" ] }
shlex = "1.3.0"

thiserror.workspace = true
