[package]
name = "remu_simulator_unicorn"
version = "0.1.0"
edition = "2024"

[dependencies]
remu_simulator = { path = "../.." }
remu_state = { path = "../../../remu_state" }
remu_types = { path = "../../../remu_types" }

unicorn-engine = { version = "2.1" }
