[package]
name = "remu_fmt"
version = "0.1.0"
edition = "2024"

[dependencies]
remu_macro = { path = "../remu_macro" }
remu_types = { path = "../remu_types" }
thiserror.workspace = true

tracing.workspace = true

winnow.workspace = true
target-lexicon.workspace = true
capstone = "0.14.0"
