[package]
name = "remu_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
remu_macro = { path = "../remu_macro" }
remu_logger = { path = "../remu_logger" }
remu_core = { path = "../remu_core" }

clap = { workspace = true, features = [ "derive", "color" ] }

tracing.workspace = true

anyhow.workspace = true

petgraph.workspace = true

crossterm = "0.29.0"
nu-ansi-term = "0.50.3"
reedline = "0.44.0"

pest.workspace = true
pest_derive.workspace = true
