[package]
name = "remu_simulator_spike"
version = "0.1.0"
edition = "2024"

[dependencies]
remu_simulator = { path = "../.." }
remu_state = { path = "../../../remu_state" }
remu_types = { path = "../../../remu_types" }

[build-dependencies]
cc = "1.2.55"
