[package]
name = "remu_types"
version = "0.1.0"
edition = "2024"

[dependencies]
remu_macro = { path = "../remu_macro" }
thiserror.workspace = true
tracing.workspace = true

target-lexicon.workspace = true
